name: ucp1pamlanjut
description: "A new Flutter module project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/profil2.jpg
    - assets/food_banner.jpg
    - assets/dashboard.png

  module:
    androidX: true
    androidPackage: com.example.ucp1pamlanjut
    iosBundleIdentifier: com.example.ucp1pamlanjut
